### ISSUE TITLE
Issue with many levels of dependencies

### ISSUE THREAD

**Issue by DaBs** [HerringtonDarkholme/gulp-progeny#13]
I'm currently having an issue where updating a grand-grand-grand parent fil does not trigger the correct changes. My structure right now looks like this, where `->` is an import statement:

richtext-custom-class.less -> "./Mixins/_mixins.less" -> "../../../../../someotherfile.less" -> "../../../../../somethirdfile.less" -> "./Mixins/TheStyleImChanging.less". In this case, richtext-custom-class does not update properly, or at all, when changing TheStyleImChanging. The documentation doesn't make it clear whether or not this is a limitation.

**Comment by HerringtonDarkholme** [comment]
Can you give a minimal example? I think this is a bug.

**Comment by DaBs** [comment]
I cannot replicate this in a directory setup solely for this. If I figure out what my original problem was, and if it was a bug, I'll comment here.

**Comment by Saturate** [comment]
Seems like it's pretty limited on what it supports when including files. We had the problem where it did not included import statements like this:

```
@import (reference) "Mixins/_mixins.less";
```
and 
```
@import url("Mixins/_mixins.less");
```

The first one is allowed, and is in the spec (http://lesscss.org/features/#import-options). The second one is not in the spec but it's basic css, that works in less, it will load and compile it.

This plugin is easily extended to allow the first issue with a new regex, 

`/^\s*@import\s*(?:\(\w+\)\s*)?['"]([^'"]+)['"]/`

But the second one is not fixed with a regex as it failes:

`/^\s*@import\s*(?:\(\w+\)\s*)?(?:['"]([^'"]+)['"]|url\(['"]([^'"]+)['"]\))/`

error: 
```
[13:06:45] File Changed: Website\Components\Tips\layout.less
[13:06:45] Compile: Website\Components\Tips\layout.less
C:\Projects\TestProject\node_modules\gulp-progeny\dest\parse.js:92
      if (path[0] === '/' || !parentPath) {
              ^

TypeError: Cannot read property '0' of undefined
    at C:\Projects\TestProject\node_modules\gulp-progeny\dest\parse.js:92:15
    at Array.map (native)
    at parseDeps (C:\Projects\TestProject\node_modules\gulp-progeny\dest\parse.js:152:67)
    at C:\Projects\TestProject\node_modules\gulp-progeny\dest\parse.js:193:5
    at C:\Projects\TestProject\node_modules\gulp-progeny\dest\index.js:42:12
    at Transform._transform (C:\Projects\TestProject\node_modules\gulp-progeny\dest\index.js:82:5)
    at Transform._read (C:\Projects\TestProject\node_modules\gulp-progeny\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Transform._write (C:\Projects\TestProject\node_modules\gulp-progeny\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\Projects\TestProject\node_modules\gulp-progeny\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\Projects\TestProject\node_modules\gulp-progeny\node_modules\readable-stream\lib\_stream_writable.js:227:5)
```

I guess that the first one would be nice to have fixed, and I can create a PR. But the second one, I don't know about as it's not in the spec. What do you say?

**Comment by HerringtonDarkholme** [comment]
@Saturate I think both can be supported. The problem here is that dependencies are extracted by the first matching part of regex. In the case you write, `url` part is the second one and is not extracted.

I will give it a try.

**Comment by Saturate** [comment]
@HerringtonDarkholme Super cool, I was thinking that my group `(?:(SOMETHING)|(SOMETHINGELSE))` would always be the frist match. RegEx is hard I guess :-)

Let me know if you need something! :-)

**Comment by HerringtonDarkholme** [comment]
@Saturate Give it a try?
https://github.com/HerringtonDarkholme/gulp-progeny/commit/119007119b10a95860bd6a7a2c0ebb2d3ec9b51a in 0.2.2

This regex is not very strict. But gulp-progeny does not care more dependencies are fed to it.

**Comment by Saturate** [comment]
@HerringtonDarkholme I'll try it now, I just made my own that might work as well: `^\s*@import\s*(?:\(\w+\)\s*)?(?:url\()?['"]([^'"]+)['"]`

**Comment by HerringtonDarkholme** [comment]
PR is welcome if you find problem in current approach :)

**Comment by Saturate** [comment]
So it seems to pass all my own UNIT tests and should work (https://regex101.com/r/eU7bT5/2).

However it's not working correctly yet. :-(

Consider this dependency structure:
`Component.less -> Mixins/GeneralMixin.less -> Mixins/SubMixin.less`

With `@import url("SubMixin.less")`, when I edit `SubMixin.less` it does not compile any files. However it does compile `Component.less` if I edit `GeneralMixin.less`.

If I import it with `@import (reference) "SubMixin.less"` or  `@import "SubMixin.less"` it works no matter what files I edit, as it should.

So it seems something is work with the `@import url("")` method, do you have an idea on why?

**Comment by HerringtonDarkholme** [comment]
Need More info.

You can add a `debug: true` option to your config, so every dependency is print out to stdout.

**Comment by Saturate** [comment]
It's only caputing it's own dependencies:

Inside the file:
```
@import "../../../Framework/Design/Styles/Mixins/GeneralMixins.less"; 
@import url("colors.less");
```

Logged to console:
``
[15:13:09] File Changed:  Project\Design\Styles\Regions\ComponentName\Mixins\text-mixins.less
DEP  Project\Design\Styles\Regions\ComponentName\Mixins\text-mixins.less
    |-- Framework\Design\Styles\Mixins\GeneralMixins.less
    |-- Project\Design\Styles\Regions\ComponentName\Mixins\colors.less
[15:13:09] File Changed: 1 item
[15:13:09] Compile: 0 items
[15:13:09] Write: 0 items
``

(Don't mind if the the paths don't match 100%, anonymized them a bit)

**Comment by HerringtonDarkholme** [comment]
It's strange...
Can you open a new issue and post a minimal setup for this?

**Comment by Saturate** [comment]
Not that strange anyway, forgot that we overwrote the regex two places, both where we parse all files and then for all incremental builds, now it's working perfect. Thanks!
